baseURL = "http://example.org/"
languageCode = "en-us"
title = "Welcome to my Blog"
paginate = 5

copyright = "© Dariusz Kajtoch"

[[module.imports]]
path = "github.com/chollinger93/ink-free"

[permalinks]
  posts = "/:year/:month/:title"

[params]
	subtitle = "Hi, my name is Dariusz Kajtoch. I'm interested in Science & Technology."

	# Optional 64x64 avatar image.
	avatar = "https://static.wikia.nocookie.net/deathstranding/images/e/e1/Higgs_headshot.jpg"
	featherIconsCDN = false
	mode = "auto"

	# Enable a table of contents:
	# Either "static"/true, "floating", "both", or "none" (default: static)
	# The floating TOC dissapears on mobile and adds 200px vertical space
	toc = "both"
	# Whether to truncate everything but H1/H2 headings if the last element in a TOC isn't visible. Enabled by default
	enableTocTrunate = true

	# Max tags
	maxTags = 7

	# Define words per minute to approximate reading time
	wpm = 250

	# Github base url
	github = "https://github.com/chollinger93/ink-free"

	# For statistics, we can compare the total word count against a book of your choice
	statisticsEnabled = false
	referenceBookWords = 11500.0
	referenceBook = "The Metamorphosis"
	referenceAuthor = "Franz Kafka"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/dkajtoch"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/dariusz_kajtoch"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://linkedin.com/in/dariusz-kajtoch"

#[[params.social]]
#name = "RSS"
#icon = "rss"
#url = "/index.xml"